### ISSUE TITLE
Engine sound keeps on playing when player is death.

### ISSUE THREAD

**Issue by debagos** [APercy/demoiselle#1]
First, **great mod**, again @APercy :sunglasses:

On thing I noticed during testing:
When you die while flying a demoiselle, there is no way to stop the engine sound expect for leaving the game.

Related suggestion:
When you unmount from a demoiselle, stop the engine sound and play the same sound (pitch) at the position where the demoiselle stands.

**Comment by APercy** [comment]
Oh! Thank you! I'll fix it!

**Comment by APercy** [comment]
Fixed!

**Comment by debagos** [comment]
Thanks for fixing :smiley: 
Your mod is now installed on my server hehe
