### ISSUE TITLE
Bug: Attempt to index local 'seat', a nil value.

### ISSUE THREAD

**Issue by debagos** [APercy/demoiselle#2]
My server keeps crashing with this error message:
`Runtime error from mod 'demoiselle' in callback on_playerReceiveFields():
demoiselle_forms.lua:9: attempt to index local 'seat' (a nil value)`
Traceback:
`demoiselle_forms.lua:9: in function 'getPlaneFromPlayer'
demoiselle_forms.lua:28: in function demoiselle_forms.lua:25`

**Comment by APercy** [comment]
Fixed now!
Thank you!

**Comment by debagos** [comment]
Thank you for the quick fix! :heart:
